package com.paperstack.domain.model

data class ArxivCategory(
    val code: String,
    val name: String,
    val group: String,
)

val ARXIV_CATEGORIES: List<ArxivCategory> = listOf(
    // Computer Science
    ArxivCategory("cs.AI", "Artificial Intelligence", "Computer Science"),
    ArxivCategory("cs.AR", "Hardware Architecture", "Computer Science"),
    ArxivCategory("cs.CC", "Computational Complexity", "Computer Science"),
    ArxivCategory("cs.CE", "Computational Engineering, Finance, and Science", "Computer Science"),
    ArxivCategory("cs.CG", "Computational Geometry", "Computer Science"),
    ArxivCategory("cs.CL", "Computation and Language", "Computer Science"),
    ArxivCategory("cs.CR", "Cryptography and Security", "Computer Science"),
    ArxivCategory("cs.CV", "Computer Vision and Pattern Recognition", "Computer Science"),
    ArxivCategory("cs.CY", "Computers and Society", "Computer Science"),
    ArxivCategory("cs.DB", "Databases", "Computer Science"),
    ArxivCategory("cs.DC", "Distributed, Parallel, and Cluster Computing", "Computer Science"),
    ArxivCategory("cs.DL", "Digital Libraries", "Computer Science"),
    ArxivCategory("cs.DM", "Discrete Mathematics", "Computer Science"),
    ArxivCategory("cs.DS", "Data Structures and Algorithms", "Computer Science"),
    ArxivCategory("cs.ET", "Emerging Technologies", "Computer Science"),
    ArxivCategory("cs.FL", "Formal Languages and Automata Theory", "Computer Science"),
    ArxivCategory("cs.GR", "Graphics", "Computer Science"),
    ArxivCategory("cs.GT", "Computer Science and Game Theory", "Computer Science"),
    ArxivCategory("cs.HC", "Human-Computer Interaction", "Computer Science"),
    ArxivCategory("cs.IR", "Information Retrieval", "Computer Science"),
    ArxivCategory("cs.IT", "Information Theory", "Computer Science"),
    ArxivCategory("cs.LG", "Machine Learning", "Computer Science"),
    ArxivCategory("cs.LO", "Logic in Computer Science", "Computer Science"),
    ArxivCategory("cs.MA", "Multiagent Systems", "Computer Science"),
    ArxivCategory("cs.MM", "Multimedia", "Computer Science"),
    ArxivCategory("cs.NA", "Numerical Analysis", "Computer Science"),
    ArxivCategory("cs.NE", "Neural and Evolutionary Computing", "Computer Science"),
    ArxivCategory("cs.NI", "Networking and Internet Architecture", "Computer Science"),
    ArxivCategory("cs.OS", "Operating Systems", "Computer Science"),
    ArxivCategory("cs.PF", "Performance", "Computer Science"),
    ArxivCategory("cs.PL", "Programming Languages", "Computer Science"),
    ArxivCategory("cs.RO", "Robotics", "Computer Science"),
    ArxivCategory("cs.SC", "Symbolic Computation", "Computer Science"),
    ArxivCategory("cs.SD", "Sound", "Computer Science"),
    ArxivCategory("cs.SE", "Software Engineering", "Computer Science"),
    ArxivCategory("cs.SI", "Social and Information Networks", "Computer Science"),
    ArxivCategory("cs.SY", "Systems and Control", "Computer Science"),

    // Electrical Engineering and Systems Science
    ArxivCategory("eess.AS", "Audio and Speech Processing", "Electrical Engineering and Systems Science"),
    ArxivCategory("eess.IV", "Image and Video Processing", "Electrical Engineering and Systems Science"),
    ArxivCategory("eess.SP", "Signal Processing", "Electrical Engineering and Systems Science"),
    ArxivCategory("eess.SY", "Systems and Control", "Electrical Engineering and Systems Science"),

    // Mathematics
    ArxivCategory("math.AC", "Commutative Algebra", "Mathematics"),
    ArxivCategory("math.AG", "Algebraic Geometry", "Mathematics"),
    ArxivCategory("math.AP", "Analysis of PDEs", "Mathematics"),
    ArxivCategory("math.AT", "Algebraic Topology", "Mathematics"),
    ArxivCategory("math.CA", "Classical Analysis and ODEs", "Mathematics"),
    ArxivCategory("math.CO", "Combinatorics", "Mathematics"),
    ArxivCategory("math.CT", "Category Theory", "Mathematics"),
    ArxivCategory("math.CV", "Complex Variables", "Mathematics"),
    ArxivCategory("math.DG", "Differential Geometry", "Mathematics"),
    ArxivCategory("math.DS", "Dynamical Systems", "Mathematics"),
    ArxivCategory("math.FA", "Functional Analysis", "Mathematics"),
    ArxivCategory("math.GN", "General Topology", "Mathematics"),
    ArxivCategory("math.GR", "Group Theory", "Mathematics"),
    ArxivCategory("math.GT", "Geometric Topology", "Mathematics"),
    ArxivCategory("math.HO", "History and Overview", "Mathematics"),
    ArxivCategory("math.LO", "Logic", "Mathematics"),
    ArxivCategory("math.MG", "Metric Geometry", "Mathematics"),
    ArxivCategory("math.MP", "Mathematical Physics", "Mathematics"),
    ArxivCategory("math.NA", "Numerical Analysis", "Mathematics"),
    ArxivCategory("math.NT", "Number Theory", "Mathematics"),
    ArxivCategory("math.OA", "Operator Algebras", "Mathematics"),
    ArxivCategory("math.OC", "Optimization and Control", "Mathematics"),
    ArxivCategory("math.PR", "Probability", "Mathematics"),
    ArxivCategory("math.QA", "Quantum Algebra", "Mathematics"),
    ArxivCategory("math.RA", "Rings and Algebras", "Mathematics"),
    ArxivCategory("math.RT", "Representation Theory", "Mathematics"),
    ArxivCategory("math.SG", "Symplectic Geometry", "Mathematics"),
    ArxivCategory("math.SP", "Spectral Theory", "Mathematics"),
    ArxivCategory("math.ST", "Statistics Theory", "Mathematics"),

    // Physics — Astrophysics
    ArxivCategory("astro-ph.CO", "Cosmology and Nongalactic Astrophysics", "Physics"),
    ArxivCategory("astro-ph.EP", "Earth and Planetary Astrophysics", "Physics"),
    ArxivCategory("astro-ph.GA", "Astrophysics of Galaxies", "Physics"),
    ArxivCategory("astro-ph.HE", "High Energy Astrophysical Phenomena", "Physics"),
    ArxivCategory("astro-ph.IM", "Instrumentation and Methods for Astrophysics", "Physics"),
    ArxivCategory("astro-ph.SR", "Solar and Stellar Astrophysics", "Physics"),

    // Physics — Condensed Matter
    ArxivCategory("cond-mat.dis-nn", "Disordered Systems and Neural Networks", "Physics"),
    ArxivCategory("cond-mat.mes-hall", "Mesoscale and Nanoscale Physics", "Physics"),
    ArxivCategory("cond-mat.mtrl-sci", "Materials Science", "Physics"),
    ArxivCategory("cond-mat.quant-gas", "Quantum Gases", "Physics"),
    ArxivCategory("cond-mat.soft", "Soft Condensed Matter", "Physics"),
    ArxivCategory("cond-mat.stat-mech", "Statistical Mechanics", "Physics"),
    ArxivCategory("cond-mat.str-el", "Strongly Correlated Electrons", "Physics"),
    ArxivCategory("cond-mat.supr-con", "Superconductivity", "Physics"),

    // Physics — General
    ArxivCategory("gr-qc", "General Relativity and Quantum Cosmology", "Physics"),
    ArxivCategory("hep-ex", "High Energy Physics — Experiment", "Physics"),
    ArxivCategory("hep-lat", "High Energy Physics — Lattice", "Physics"),
    ArxivCategory("hep-ph", "High Energy Physics — Phenomenology", "Physics"),
    ArxivCategory("hep-th", "High Energy Physics — Theory", "Physics"),
    ArxivCategory("math-ph", "Mathematical Physics", "Physics"),
    ArxivCategory("nucl-ex", "Nuclear Experiment", "Physics"),
    ArxivCategory("nucl-th", "Nuclear Theory", "Physics"),
    ArxivCategory("physics.ao-ph", "Atmospheric and Oceanic Physics", "Physics"),
    ArxivCategory("physics.app-ph", "Applied Physics", "Physics"),
    ArxivCategory("physics.atom-ph", "Atomic Physics", "Physics"),
    ArxivCategory("physics.bio-ph", "Biological Physics", "Physics"),
    ArxivCategory("physics.chem-ph", "Chemical Physics", "Physics"),
    ArxivCategory("physics.comp-ph", "Computational Physics", "Physics"),
    ArxivCategory("physics.flu-dyn", "Fluid Dynamics", "Physics"),
    ArxivCategory("physics.ins-det", "Instrumentation and Detectors", "Physics"),
    ArxivCategory("physics.med-ph", "Medical Physics", "Physics"),
    ArxivCategory("physics.optics", "Optics", "Physics"),
    ArxivCategory("physics.plasm-ph", "Plasma Physics", "Physics"),
    ArxivCategory("physics.soc-ph", "Physics and Society", "Physics"),
    ArxivCategory("quant-ph", "Quantum Physics", "Physics"),

    // Statistics
    ArxivCategory("stat.AP", "Applications", "Statistics"),
    ArxivCategory("stat.CO", "Computation", "Statistics"),
    ArxivCategory("stat.ME", "Methodology", "Statistics"),
    ArxivCategory("stat.ML", "Machine Learning", "Statistics"),
    ArxivCategory("stat.OT", "Other Statistics", "Statistics"),
    ArxivCategory("stat.TH", "Statistics Theory", "Statistics"),

    // Quantitative Biology
    ArxivCategory("q-bio.BM", "Biomolecules", "Quantitative Biology"),
    ArxivCategory("q-bio.CB", "Cell Behavior", "Quantitative Biology"),
    ArxivCategory("q-bio.GN", "Genomics", "Quantitative Biology"),
    ArxivCategory("q-bio.MN", "Molecular Networks", "Quantitative Biology"),
    ArxivCategory("q-bio.NC", "Neurons and Cognition", "Quantitative Biology"),
    ArxivCategory("q-bio.PE", "Populations and Evolution", "Quantitative Biology"),
    ArxivCategory("q-bio.QM", "Quantitative Methods", "Quantitative Biology"),
    ArxivCategory("q-bio.TO", "Tissues and Organs", "Quantitative Biology"),

    // Quantitative Finance
    ArxivCategory("q-fin.CP", "Computational Finance", "Quantitative Finance"),
    ArxivCategory("q-fin.EC", "Economics", "Quantitative Finance"),
    ArxivCategory("q-fin.MF", "Mathematical Finance", "Quantitative Finance"),
    ArxivCategory("q-fin.PM", "Portfolio Management", "Quantitative Finance"),
    ArxivCategory("q-fin.PR", "Pricing of Securities", "Quantitative Finance"),
    ArxivCategory("q-fin.RM", "Risk Management", "Quantitative Finance"),
    ArxivCategory("q-fin.ST", "Statistical Finance", "Quantitative Finance"),
    ArxivCategory("q-fin.TR", "Trading and Market Microstructure", "Quantitative Finance"),

    // Economics
    ArxivCategory("econ.EM", "Econometrics", "Economics"),
    ArxivCategory("econ.GN", "General Economics", "Economics"),
    ArxivCategory("econ.TH", "Theoretical Economics", "Economics"),
)
